-- VM 2026 — kun gruppespill-2 (Runde 2). Trygt å lime inn alene i Supabase → SQL Editor.
-- Rører KUN gruppespill-2-raden (upsert). Ingen andre quizer berøres.
-- Etter innliming står den 'locked'. Flip til open når du vil publisere (egen kommando nederst i utkastet).

insert into public.event_quizzes (event_id, slug, num, phase, title, sub, hero_img, difficulty, questions, status, sort, published)
values (
  'vm-2026', 'gruppespill-2', '09', 'Gruppespill omgang 2',
  'Runde 2 — VM tar form', 'Norge braker løs, Messi- og Mbappé-rekorder og Canadas målfest — kampene 15.–18. juni.', 'vm-gruppespill-1', 'middels',
  '[{"category": "Norge", "q": "Norge åpnet VM med solid seier 16. juni. Hva ble resultatet mot Irak?", "options": ["2–1", "3–3", "1–0", "4–1"], "correct": 3, "explanation": "Norge vant 4–1 i sin første VM-kamp på 28 år og toppet gruppe I på målforskjell foran Frankrike."}, {"category": "Haaland", "q": "Erling Haaland scoret sine aller første VM-mål mot Irak. Hvor mange ble det?", "options": ["To", "Null", "Ett", "Tre"], "correct": 0, "explanation": "Haaland scoret to mål (29. og 43. minutt) på sin VM-debut da Norge slo Irak 4–1."}, {"category": "Messi-rekord", "q": "Argentina slo Algerie 3–0. Hva gjorde Lionel Messi i kampen?", "options": ["Scoret ett mål fra straffe", "Ble utvist", "Stod over kampen med skade", "Scoret hat-trick og tangerte Kloses VM-målrekord"], "correct": 3, "explanation": "Messi scoret tre og tangerte Miroslav Kloses rekord på 16 VM-mål — hans første hat-trick i et VM, på sin 200. landskamp."}, {"category": "Mbappé", "q": "Frankrike vant 3–1 over Senegal. Hva ble Kylian Mbappé etter sine to mål?", "options": ["Byttet ut i pausen", "Frankrikes mestscorende landslagsspiller gjennom tidene", "Toppscorer i hele VM-historien", "Utvist i sluttminuttene"], "correct": 1, "explanation": "Mbappés dobbel sendte ham forbi alle andre på Frankrikes evige scoringsliste."}, {"category": "Skrell", "q": "Hvilket lag holdt storfavoritten Spania til 0–0 i åpningskampen?", "options": ["Marokko", "Panama", "Kapp Verde", "Haiti"], "correct": 2, "explanation": "VM-debutant Kapp Verde tok et sensasjonelt poeng mot Spania, med målvakt Vozinha som den store helten."}, {"category": "England", "q": "England slo Kroatia 4–2. Hvem scoret to av målene?", "options": ["Harry Kane", "Bukayo Saka", "Marcus Rashford", "Jude Bellingham"], "correct": 0, "explanation": "Kane scoret to, mens Bellingham og Rashford scoret ett hver i en målrik åpningskamp."}, {"category": "Målfest", "q": "Vertsnasjonen Canada knuste Qatar i sin andre kamp. Hva ble resultatet?", "options": ["2–0", "3–1", "1–0", "6–0"], "correct": 3, "explanation": "Canada vant 6–0 med hat-trick av Jonathan David — tidenes største VM-seier for et CONCACAF-lag."}, {"category": "Først videre", "q": "Hvilket vertsland ble det aller første laget som sikret avansement, etter 1–0 mot Sør-Korea?", "options": ["USA", "Canada", "Mexico", "Brasil"], "correct": 2, "explanation": "Mexico slo Sør-Korea 1–0 og ble første lag klar for sluttspillet i VM 2026."}, {"category": "Debutant", "q": "Colombia vant 3–1 i sin åpningskamp. Mot hvilken VM-debutant?", "options": ["Jordan", "Curaçao", "Usbekistan", "Kapp Verde"], "correct": 2, "explanation": "Colombia slo VM-debutant Usbekistan 3–1 i gruppe K."}, {"category": "Uavgjort", "q": "Cristiano Ronaldos Portugal måtte nøye seg med uavgjort i åpningskampen. Mot hvem?", "options": ["DR Kongo", "Panama", "Marokko", "Usbekistan"], "correct": 0, "explanation": "Portugal og DR Kongo spilte 1–1 i gruppe K."}]'::jsonb, 'locked', 9, true
)
on conflict (event_id, slug) do update set
  num=excluded.num, phase=excluded.phase, title=excluded.title, sub=excluded.sub,
  hero_img=excluded.hero_img, difficulty=excluded.difficulty, questions=excluded.questions,
  status=excluded.status, sort=excluded.sort, published=excluded.published;
